language: node_js
node_js:
  - "6"
git:
    submodules: false
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
notifications:
    slack:
        rooms:
            secure: evlKaJ9RVVmD3jcs2W/itnvZk+9Dbp5ZnbAr+03DoQOxao2m2wKTq3D1qQbw34yDOQ5Blk6XOSk6QDs2D2j9Kdsh0BT7k/EZHDCKgIlvG7Vz3ZLXd1c7xJCoooheRLxpwUOsoIxjeKt4VzKdlwqXJbEQ0NxAzXiM9HZtR7+Ndctkxt5TD1tebh2vb7nxeUhvlGB93VvUelO72m+3MZW6jhJKPxZVc3M9W8ZnpY5Xz+QGbevvbi+Gs8fqmDVA3cS9dPTZ5YD7UtJ6MUX9fDbxBtc8PovSSkpVCsqI6sNM3iitBsF6GuFfIwVu5JzO5nQGvmV3FVvbl+5QNBJ4fNz8AtEeVW54fFnk1zz0GqhmiIVCkaCc6XjkH6vtGiCTaZNO26vfQXWhxPCbdjJ4BD8l9xVcgIctoQGqWLqaNQrV18HPSR+cp2lQbmVDssAoJzkVhkwDAW/iedfNua+maSxh7d2mP4vWf0dEYhh2U2ziEc31523utdjYhDiy7I1RIT0eVIhpmyKK085UXRAYh0WDsORRENszs4xLz7Ea7Ts34I9gc/oc4PRmOY2SjESnwMHFm8tkYkF6xoUNmMfKfCA/z264oplHCdU8tCtFsHmrUUKc4SiPD+c+bV1hyXcKYJgstXsDn3yBQ1rXBUNk1AC6VzbZFJcYWcndmAYH82BdTMY=
        on_success: always
